/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2024-01-11 02:00:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._06Session;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class PwForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	*{padding: 0;font-size: 12px;}\r\n");
      out.write("	h2{font-size: 25px;font-family: 굴림;}\r\n");
      out.write("	#AllWrap{margin:0 auto; text-align:center; align:center;}\r\n");
      out.write("	#RadioBox{margin:0 0 10px 0;text-align:left;}\r\n");
      out.write("	#IdBox{border:10px solid rgb(218, 218, 218);padding: 10px; width: 50%;  }\r\n");
      out.write("	#InputTable{border:0px solid red; border-spacing: 0; border-collapse: collapse;}        \r\n");
      out.write("	#InputTable th{text-align:left; padding: 10px;}\r\n");
      out.write("	#InputTable td{text-align:left; padding: 10px;}\r\n");
      out.write("	#InputTable input{border:1px solid gray;height: 23px;padding:0 0 0 3px;}\r\n");
      out.write("	#InputTable select{border:1px solid gray;height: 25px;padding: 4px;}\r\n");
      out.write("	#btn{\r\n");
      out.write("	    background-color: rgb(212, 0, 0);color: white;padding: 5px 20px;border:0;\r\n");
      out.write("	    font-size: 13px;font-weight: bold;border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.bullet{color: red;font-weight: bold;margin-right: 5px;font-size: 16px;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Common/Link.jsp", out, false);
      out.write("\r\n");
      out.write("	<div style=\"margin-top:30px;\"></div>\r\n");
      out.write("	<div id=\"AllWrap\" >\r\n");
      out.write("		<h2>비밀번호 찾기</h2>\r\n");
      out.write("		<div style=\"margin-top:30px;\"></div>\r\n");
      out.write("	<div id=\"IdBox\">\r\n");
      out.write("	<table id=\"InputTable\" align=\"center\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("			<col width=\"30%\" />\r\n");
      out.write("			<col width=\"70%\" />\r\n");
      out.write("		</colgroup>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th><span class=\"bullet\">&gt;</span><strong>아이디</strong></th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"\" style=\"width:200px;\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th><span class=\"bullet\">&gt;</span><strong>이름(대표자명)</strong></th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"\" style=\"width:200px;\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>\r\n");
      out.write("				<span class=\"bullet\">&gt;</span><strong>휴대전화</strong></th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"\" style=\"width:40px;\"> -\r\n");
      out.write("				<input type=\"text\" name=\"\" style=\"width:50px;\"> -\r\n");
      out.write("				<input type=\"text\" name=\"\" style=\"width:50px;\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<div>\r\n");
      out.write("		<img src=\"./images/g_line.gif\" width=\"400\" height=\"1\" border=\"0\" />\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("		비밀번호를 찾기 위해서 아이디, 이름, 휴대전화를 입력하세요.\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>    \r\n");
      out.write("	<div style=\"margin-top:20px;\">\r\n");
      out.write("		<input type=\"button\" value=\"아이디 찾기 &gt;\" id=\"btn\">\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
